var age = 20;
age = true;
console.log(age);
age = 'hello';
console.log(age);
age = { name: 'luigi' };
console.log(age);
var mixed = [];
mixed.push(5);
mixed.push('shohedul');
mixed.push(false);
console.log(mixed);
var person;
person = { name: 'shohedul', age: 25 };
console.log(person);
person = { name: 25, age: 'shohedul' };
console.log(person);
